# http://travis-ci.org/mpi4py/mpi4py

language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

os: linux
dist: trusty
sudo: required

env:
  global:
    - HYDRA_LAUNCHER=fork
  matrix:
    - MPI=mpich
    - MPI=openmpi

matrix:
  include:
    - os: osx
      env: MPI=mpich PY=
      language: generic
      python: 2
    - os: osx
      env: MPI=openmpi PY=
      language: generic
      python: 2
    - os: osx
      env: MPI=mpich PY=3
      language: generic
      python: 3
    - os: osx
      env: MPI=openmpi PY=3
      language: generic
      python: 3
    - python: pypy
    - python: pypy3
  allow_failures:
    - python: pypy
    - python: pypy3

branches:
  only:
    - master
    - maint

git:
  depth: 3

cache:
  apt: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $MPI; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python$PY; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip$PY install numpy; fi
  - sh ./conf/travis/install-mpi.sh $MPI
  - pip$PY install Cython
  - cython --version
install:
  - pip$PY -vvv install .

before_script:
  - if [[ "$MPI" == "mpich" ]]; then P=2; else P=5; fi
script:
  - mpiexec -n 1  python$PY $PWD/test/runtests.py -v -f --no-builddir --exclude=spawn
  - mpiexec -n $P python$PY $PWD/test/runtests.py -v -f --no-builddir --exclude=spawn

#notifications:
#  email: false
